Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine318"
  config.vm.box_version = "4.3.12"
  config.vm.hostname = "jcarioS"
  config.vm.network "private_network", ip: "192.168.56.110"

  config.vm.provision "shell",
    name: "init",
    path: "init.sh"

  config.vm.synced_folder "shared/", "/shared"
end
