Vagrant.configure("2") do |config|
  config.vm.box = "terrywang/archlinux"
  config.vm.box_version = "4.24.0529"

  config.vm.define "jcarioS" do |control|
    control.vm.hostname = "jcarioS"
    control.vm.provision "shell", name: "init", path: "init.sh"
    control.vm.network "private_network", ip: "192.168.56.110"
  end

  config.vm.define "jcarioSW" do |control|
    control.vm.hostname = "jcarioSW"
    control.vm.provision "shell", name: "init", path: "init.sh"
    control.vm.network "private_network", ip: "192.168.56.111" # yeah it isnt on eth1 i dont get why
  end
end
